### ISSUE TITLE
Allow overriding in the PasswordGenerator class

### ISSUE THREAD

**Issue by bsoyka** [bsoyka/passwd#14]
<div align="center">
<strong>
Thanks for taking the time to contribute! 🥳
</strong>
<br><br>
<em>
Please be sure to check out our <a href="https://github.com/bsoyka/passwd/blob/master/CONTRIBUTING.md">contributing guidelines</a> and <a href="https://github.com/bsoyka/passwd/blob/master/CODE_OF_CONDUCT.md">code of conduct</a> before helping out.
</em>
</div>

---

All the properties available in the `__init__` method of the `PasswordGenerator` class should *also* be available in the `generate` method, and any arguments specified in the `generate` method should take precedence.

For example, take a look at this code:

```py
pass_gen = PasswordGenerator(8, uppercase=False, special=False)

pass_gen.generate(length=8, uppercase=True, lowercase=True)
```

In the example above, the `generate` method should end up generating a password using the values in the **Final Value** column below:

|     Argument    | Final Value | Default | `__init__` | `generate` |
|:---------------:|:-----------:|:-------:|:----------:|:----------:|
|   **`length`**  |   **`8`**   |         |     `8`    |     `8`    |
| **`uppercase`** |  **`True`** |  `True` |   `False`  |   `True`   |
| **`lowercase`** |  **`True`** |  `True` |            |   `True`   |
|   **`digits`**  |  **`True`** |  `True` |            |            |
|  **`special`**  | **`False`** |  `True` |   `False`  |            |

If you take a look at the table above, the value farthest to the right is always the final value.

The value that's given in the `generate` call should always be used first if there is one, then the value from `__init__`, then the default value.

**Comment by echang97** [comment]
Hi @bsoyka! Just made a PR for this issue if you want to look over it
